### ISSUE TITLE
When DELETEGRP function is called main page dissappears

### ISSUE THREAD

**Issue by tototto** [AY2021S2-TIC4002-F18-3/tp2#93]
Steps to replicate
1) use delete group [e.g.] "deletegrp 4"
2) all contact disappear

**Current Behaviour**
- the list of contact all disappear
![image](https://user-images.githubusercontent.com/43071400/113498837-3a655900-9543-11eb-8dd5-b0beb870091b.png)

**Expected Behaviour**
- the list of contact should not disappear but still remain

**Comment by JanuariusJang** [comment]
Changed code to update list of all contacts after performing the deletion of group.
![Screenshot 2021-04-06 at 10 56 29 PM](https://user-images.githubusercontent.com/43991396/113731701-8ffc5a00-972b-11eb-8523-a065b75ab5da.png)
